name: WSpawners
version: '${project.version}'
main: com.wynvers.spawners.WSpawners
api-version: '1.20'
description: Custom spawner management plugin
softdepend: [MythicMobs]
commands:
  spawner:
    description: Manage custom spawners
    usage: /<command> <give|list|reload|myspawners|info> [player] [spawner_id]
    permission: wspawners.command
permissions:
  wspawners.command:
    description: Allows use of the spawner command
    default: op
  wspawners.use:
    description: Allows players to place and recover their own spawners
    default: true
